### PR TITLE
Try to handle the sync_lazy TODOs in matching.ml and translcore.ml

### PR DESCRIPTION
**Pull request by gasche**
These are just a late-night experiment, I have not tried the code or even compiled it, but in case it may help...

(There is a TODO remaining in genprintval.ml, left for another day.)

The matching.ml change may seem like it's cheating, but in fact I don't think that there will be any performance impact, and it nicely simplifies the code.

### CODE REVIEW

**Comment by gasche** [comment]
I pushed a proposal (again completely untested) for genprintval.ml.

Note: the pattern-matching on `Forcing | Forward | _` makes me nervous; I just checked and it happens to be compiled correctly today, but this is a coincidence, it could just as easily behave unexpectedly on values that are not blocks of tag 0. I would rather try to avoid it.

**Comment by gadmm** [comment]
Thanks. Note that the pattern-matching trick is already used in CamlinternalOO, so I suggest it is fine to use it while it is used elsewhere. It would be nicer to have some kind of constructor unboxing in the compiler, of course.

**Comment by gadmm** [comment]
The proposal for matching.ml is bold, I like it. One more simplification of this approach!

**Comment by gadmm** [comment]
I'll merge first and then test/rebase locally.

**Pull request merged**
